development:
  adapter: postgresql
  database: taganoid_development
  encoding: UTF8
  username: taganoid
  password: taganoid
  port: 5432
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: taganoid_test
  encoding: UTF8
  username: taganoid
  password: taganoid
  port: 5432
  host: localhost
  min_messages: warning

staging:
  adapter: postgresql
  database: taganoid_staging
  encoding: UTF8
  username: taganoid
  password: taganoid
  port: 5432
  host: localhost
  min_messages: warning

production:
  adapter: postgresql
  database: taganoid_production
  encoding: UTF8
  username: taganoid
  password: taganoid
  port: 5432
  host: localhost
  min_messages: warning